CREATE TABLE IF NOT EXISTS links (
  id VARCHAR(100) PRIMARY KEY,
  destinationUrl VARCHAR(8192) NOT NULL,
	expirationTtl INT,
  namespace VARCHAR(100),
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	expiresAt TIMESTAMP
);
