CREATE TABLE IF NOT EXISTS links (
  id VARCHAR(100) PRIMARY KEY,
  destinationUrl VARCHAR(2048) NOT NULL,
  namespace VARCHAR(100),
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
